[package]
name = "rust-chat-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.28.0"
tokio = { version = "1.27", features = ["full"] }
tokio-rusqlite = "0.3.0"
